# Generated by Django 4.2.23 on 2025-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', '受諾'), ('in_progress', '配送中'), ('completed', '完了'), ('rejected', '拒否')], default='accepted', max_length=20, verbose_name='ステータス')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='集荷時刻')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='配送時刻')),
                ('driver_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='ドライバー評価')),
                ('requester_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='依頼者評価')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アサイン',
                'verbose_name_plural': 'アサイン',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件名')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('sender_name', models.CharField(max_length=100, verbose_name='差出人名')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='差出人電話番号')),
                ('sender_address', models.TextField(verbose_name='差出人住所')),
                ('sender_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='差出人緯度')),
                ('sender_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='差出人経度')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='受取人名')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='受取人電話番号')),
                ('recipient_address', models.TextField(verbose_name='配送先住所')),
                ('recipient_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='配送先緯度')),
                ('recipient_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='配送先経度')),
                ('item_name', models.CharField(max_length=200, verbose_name='荷物名')),
                ('item_quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('item_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='重量（kg）')),
                ('item_size', models.CharField(blank=True, max_length=100, verbose_name='サイズ')),
                ('delivery_date', models.DateField(verbose_name='配送希望日')),
                ('delivery_time', models.CharField(blank=True, max_length=50, verbose_name='配送希望時間')),
                ('special_instructions', models.TextField(blank=True, verbose_name='特別な指示')),
                ('estimated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='見積料金')),
                ('final_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='確定料金')),
                ('status', models.CharField(choices=[('pending', '受付中'), ('assigned', 'アサイン済み'), ('in_progress', '配送中'), ('completed', '配送完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '配送依頼',
                'verbose_name_plural': '配送依頼',
                'ordering': ['-created_at'],
            },
        ),
    ]
