# Generated by Django 4.2.23 on 2025-08-03 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='依頼者'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='delivery_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
