# Generated by Django 4.2.23 on 2025-08-03 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='割り当て者'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='driver_reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ドライバー報酬'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='seed_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'seed'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='管理シードユーザー'),
        ),
    ]
