# Generated by Django 4.2.23 on 2025-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_assignment_assigned_by_deliveryrequest_driver_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='request_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='依頼金額'),
        ),
    ]
