[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install] 
cmd = "pip install --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "python manage.py collectstatic --noinput"

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"