# Generated by Django 4.2.23 on 2025-08-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('driver', 'ドライバー'), ('company', '事業者'), ('seed', 'シードユーザー')], default='driver', max_length=20, verbose_name='ユーザータイプ'),
        ),
    ]
