"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 本番環境の判定
IS_PRODUCTION = os.environ.get('RAILWAY_ENVIRONMENT') == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-q-nhacj+2p+bsautne*czu^qhr&)^jqn#v^ke(*644u$&gu9*p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

# ALLOWED_HOSTS設定
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['*']  # 本番環境では全てのホストを許可
else:
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'apps.users',
    'apps.delivery',
    'apps.files',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# データベース設定 - PostgreSQLのみ使用
if os.environ.get('DATABASE_URL'):
    # 本番環境またはDATABASE_URLが設定されている場合
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=os.environ.get('DATABASE_URL'),
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except ImportError:
        # URLを手動でパース
        import urllib.parse as urlparse
        url = urlparse.urlparse(os.environ.get('DATABASE_URL'))
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': url.path[1:],
                'USER': url.username,
                'PASSWORD': url.password,
                'HOST': url.hostname,
                'PORT': url.port,
            }
        }
else:
    # ローカル開発環境用PostgreSQL設定
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'delivery_support_dev'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.10.4:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "http://192.168.10.4:3001",
    "http://192.168.10.4:3002",
    "https://deliverfrontend-production.up.railway.app",
    "https://deliver-frontend-production.up.railway.app",
    "https://deliveryfrontend-production.up.railway.app",
]

# デバッグ用：CORS設定の確認（本番環境でログ出力）
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

logger.info(f"🔍 CORS DEBUG - IS_PRODUCTION: {IS_PRODUCTION}")
logger.info(f"🔍 CORS DEBUG - DEBUG: {DEBUG}")
logger.info(f"🔍 CORS DEBUG - CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")

# CORS追加設定
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 開発環境では全てのオリジンを許可（デバッグ用）
if DEBUG and not IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = True
    print("WARNING: CORS_ALLOW_ALL_ORIGINS is True (Debug mode)")

# 本番環境でのCORS設定追加
if IS_PRODUCTION:
    # 緊急対策：正確なURLを強制追加
    emergency_origins = [
        "https://deliverfrontend-production.up.railway.app",
    ]
    for origin in emergency_origins:
        if origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)
            logger.info(f"🚨 Emergency CORS origin added: {origin}")
    
    # 環境変数からフロントエンドURLを取得
    frontend_url = os.environ.get('FRONTEND_URL')
    if frontend_url and frontend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(frontend_url)
        logger.info(f"✅ FRONTEND_URL added to CORS: {frontend_url}")
    
    # テスト用CORS設定（Railway環境変数から）
    test_origins = os.environ.get('ALLOWED_TEST_ORIGINS', '')
    if test_origins:
        for origin in test_origins.split(','):
            origin = origin.strip()
            if origin and origin not in CORS_ALLOWED_ORIGINS:
                CORS_ALLOWED_ORIGINS.append(origin)
                logger.info(f"✅ Test origin added to CORS: {origin}")

# 最終確認用ログ
logger.info(f"🎯 Final CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")

# CSRF設定
if IS_PRODUCTION:
    # 本番環境用のCSRF設定
    CSRF_TRUSTED_ORIGINS = [
        'https://deliverbackend-production-6353.up.railway.app',
        'https://*.up.railway.app',
    ]
    # 環境変数からの追加
    backend_url = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
    if backend_url:
        CSRF_TRUSTED_ORIGINS.append(f'https://{backend_url}')
        
    frontend_url = os.environ.get('FRONTEND_URL')
    if frontend_url and frontend_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(frontend_url)

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Claude API settings
CLAUDE_API_KEY = os.getenv('CLAUDE_API_KEY')
CLAUDE_API_URL = 'https://api.anthropic.com/v1/messages'
