# Generated by Django 4.2.23 on 2025-08-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='ファイル')),
                ('original_name', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('file_type', models.CharField(choices=[('delivery_document', '配送帳票'), ('receipt', '受領書'), ('other', 'その他')], default='delivery_document', max_length=20, verbose_name='ファイルタイプ')),
                ('file_size', models.PositiveIntegerField(verbose_name='ファイルサイズ（バイト）')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIMEタイプ')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Claude処理済み')),
                ('claude_response', models.JSONField(blank=True, null=True, verbose_name='Claude API レスポンス')),
                ('extracted_data', models.JSONField(blank=True, null=True, verbose_name='抽出データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('delivery_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='delivery.deliveryrequest', verbose_name='関連配送案件')),
            ],
            options={
                'verbose_name': 'ファイルアップロード',
                'verbose_name_plural': 'ファイルアップロード',
                'ordering': ['-created_at'],
            },
        ),
    ]
