# Generated by Django 4.2.23 on 2025-08-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_data',
            field=models.TextField(blank=True, null=True, verbose_name='ファイルデータ（Base64）'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='ファイル（旧）'),
        ),
    ]
